export const defaultSettingsData = {
  documents: [],
  team: [],
  company: {
    name: "",
    address: "",
    city: "",
    country: "",
    kvk: "",
    btw: "",
    iban: "",
    email: "",
    phone: "",
    website: "",
    signatureLegalText: "",
    footerText: "",
    defaultHourlyRate: 0,
  },
  clientNotes: [],
  lineTemplates: [],
  emailIntegration: {
    provider: "none",
    enabled: false,
    fromEmail: "",
    apiKey: "",
    confirmationEmails: [],
    documentSubjectTemplate: "",
    documentBodyTemplate: "",
    confirmationBodyTemplate: "",
    documentHtmlTemplate: "",
    confirmationHtmlTemplate: "",
    templatePresets: [],
    selectedTemplatePresetId: "",
  },
};
